version: "3"
services:
  neo4j:
    # neo4j-core gem has a bug with the 4.0.1 version
    # image: neo4j:4.0.1
    image: neo4j:3.5
    environment:
      - NEO4J_dbms_default__database=followers
    volumes:
      - "./data/:/data"
      - "./log/:/log"
    ports:
      - 7687:7687 # Bolt (binary protocol)
      - 7473:7473 # HTTPS
      - 7474:7474 # HTTP
